#!/usr/bin/env python3

import sys

if __name__ == '__main__':
    sys.set_int_max_str_digits(0)
    result = eval(sys.argv[1])
    if hasattr(result, '__iter__'):
        for val in result:
            print(val)
    else:
        print(result)
